apiVersion: v1
kind: Service
metadata:
  name: redis-1
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-1
spec:
  replicas: 1
  selector:
    name: redis-1
  template:
    metadata:
      labels:
        name: redis-1
    spec:
      containers:
      - name: redis-1
        image: freegeoip/redis:2.8
        env:
          - name: MASTER
            value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 0.2
